baseURL: "https://www.jonkatzur.com" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Jon Katzur
paginate: 5
theme: PaperMod

deployment:
  order:
    - .png$
    - .jpg$
    - .gif$
    - .svg$
  targets:
    - URL: "s3://www.jonkatzur.com?region=us-east-1"
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: "max-age=630720000, no-transform, public"
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
