baseURL: "https://www.jonkatzur.com"
paginate: 7
theme: PaperMod

params:
  homeInfoParams: 
    Title: "Hi, I'm Jon Katzur"
    Content: "I love using data to create intuitive and empathetic software."
  socialIcons:
    - name: twitter
      url: https://twitter.com/jkatzur
    - name: github
      url: https://github.com/jkatzur
    - name: linkedin
      url: https://www.linkedin.com/in/jkatzur/
  ShowBreadCrumbs: true

deployment:
  order:
    - .png$
    - .jpg$
    - .gif$
    - .svg$
  targets:
    - URL: "s3://www.jonkatzur.com?region=us-east-1"
    - cloudFrontDistributionID: "E3VNIHN614Y681"
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: "max-age=630720000, no-transform, public"
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true

menu: 
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identified: about
      name: About
      url: /about/
      weight: 20