baseURL: "https://www.jonkatzur.com"
pagination: 
  pagerSize: 7
title: "JK"
theme: PaperMod
environment: "production"

params:
  homeInfoParams: 
    Title: "Hi, I'm Jon Katzur"
    Content: |
              I love building and leading high performing data and machine learning teams.

              Now SVP Engineering at [R1](https://www.r1rcm.com/). Prior VC-backed data [founder](https://www.linkedin.com/company/proximo-data/about/),
              built teams while scaling from Series A to exit at [1010data](https://www.1010data.com/), search and AI product at pre-IPO Slack,
              eng for personalization at [Amazon](https://www.aboutamazon.com/news/retail/amazon-ai-shopping-guides-product-research-recommendations).
              
              And co-founder of Biv Capital. We buy and incubate AI-native companies driving outcomes for enterprises. Portfolio includes [ChatRank](https://chatrank.ai/) and [JustReachOut](https://justreachout.io/)
  socialIcons:
    - name: twitter
      url: https://twitter.com/jkatzur
    - name: github
      url: https://github.com/jkatzur
    - name: linkedin
      url: https://www.linkedin.com/in/jkatzur/
  ShowBreadCrumbs: true

deployment:
  order:
    - .png$
    - .jpg$
    - .gif$
    - .svg$
  targets:
    - URL: "s3://www.jonkatzur.com?region=us-east-1"
    - cloudFrontDistributionID: "E3VNIHN614Y681"
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: "max-age=630720000, no-transform, public"
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true

menu: 
  main:
    - identifier: home
      name: Home
      url: /
      weight: 5
    - identifier: writing
      name: Writing
      url: /posts/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 15
    - identifier: about
      name: About
      url: /about/
      weight: 20

googleAnalytics: "G-HSCNF59DJ5"