baseURL: "https://www.jonkatzur.com"
pagination: 
  pagerSize: 7
title: "JK"
theme: PaperMod
environment: "production"

params:
  homeInfoParams: 
    Title: "Hi, I'm Jon Katzur"
    Content: "I love building and leading high performing data and machine learning teams. I've been a [founder](https://www.linkedin.com/company/proximo-data/about/), employee [30 to 300](https://www.1010data.com/), [1200 to 2500](https://slack.com/), and now [~1.5million](https://www.amazon.com/)"
  socialIcons:
    - name: twitter
      url: https://twitter.com/jkatzur
    - name: github
      url: https://github.com/jkatzur
    - name: linkedin
      url: https://www.linkedin.com/in/jkatzur/
  ShowBreadCrumbs: true

deployment:
  order:
    - .png$
    - .jpg$
    - .gif$
    - .svg$
  targets:
    - URL: "s3://www.jonkatzur.com?region=us-east-1"
    - cloudFrontDistributionID: "E3VNIHN614Y681"
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: "max-age=630720000, no-transform, public"
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true

menu: 
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20

googleAnalytics: "G-HSCNF59DJ5"